#!/usr/bin/env python3
"""
validate_review_output.py — Validate a Computer File Steward v1 review run.

Checks:
  1. All six required review outputs exist under the run directory.
  2. INVENTORY.csv has the required columns and no reparse points were
     followed (a file/dir whose path resolves outside the explicit target).
  3. PROPOSED_ACTIONS.csv: every row has blocked=true (v1 advisory only).
  4. Secret-safety audit: no password values, API keys, OAuth tokens, private
     keys, recovery codes, .env contents, credential-bearing URLs, household
     identifiers, or content excerpts from sensitive files. Reports category
     + count only — never prints matches.
  5. Path-safety: no path outside the explicit fixture target was inventoried
     as target content.

USAGE:
    python3 validate_review_output.py --run <run-directory> --target <explicit-target>
"""
import argparse
import csv
import os
import re
import sys

# Secret patterns (test only for presence/count — never print matched values)
# Secret patterns. Explicitly NOT included here: generic hex strings of ~32/40
# chars, because git commit SHAs and SHA-256 checksums are legitimate and common
# in reports. Real secrets are caught by the specific, high-precision patterns.
SECRET_PATTERNS = {
    "api_key": re.compile(r"(?i)\b(api[_-]?key|api[_-]?token|secret[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|bearer)\s*[=:]\s*\S+"),
    "aws_key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "private_key_block": re.compile(r"-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----"),
    "openai_key": re.compile(r"\bsk-[A-Za-z0-9]{20,}\b"),
    "google_key": re.compile(r"\bAIza[0-9A-Za-z_-]{20,}\b"),
    "github_pat": re.compile(r"\bgh[pousr]_[0-9A-Za-z]{36,}\b"),
    "credential_url": re.compile(r"[a-zA-Z][a-zA-Z0-9+.-]*://[^\s/@]+:[^\s/@]+@[^\s]+"),
    "password_field": re.compile(r"(?i)\b(password|passwd|pwd|secret)\s*[=:]\s*\S+"),
    "recovery_code": re.compile(r"(?i)\b(recovery[-\s]?code|mfa[-\s]?seed|2fa[-\s]?code|otp[-\s]?secret)\s*[=:]\s*\S+"),
    "household_id": re.compile(r"(?i)\b(particulars|date\s+of\s+birth|medicare\s+no|tax\s+file\s+no|drivers?\s+licence\s+no)\b"),
}

# REQUIRED_OUTPUTS validation: VALIDATION_RESULTS.md is GENERATED by this
# validator, so it must not be required to pre-exist.
REQUIRED_PRE_EXISTING_OUTPUTS = [
    "DIRECTORY_REVIEW.md",
    "INVENTORY.csv",
    "PROPOSED_ACTIONS.csv",
    "UNKNOWNS.md",
    "RUN_METADATA.json",
]

SENSITIVE_MARKERS = ["secret", "credential", "password", "token", ".env", "key.pem",
                     "id_rsa", "bitwarden", "recovery-code", "mfa", "household",
                     "conversations.json", "clinical", "legal", "financial",
                     "mailbox", "upload", "database", "briefing"]


def normalize_path(p):
    """Convert a Windows/UNC/WSL path to a comparable canonical POSIX form.

    //wsl.localhost/Ubuntu-24.04/home/michael/...  ->  /home/michael/...
    C:/...  ->  /mnt/c/...  (not used in fixture, but harmless)
    """
    p = p.strip()
    p = p.replace("\\", "/")
    m = re.match(r"^//wsl\.localhost/([^/]+)/(.*)$", p)
    if m:
        return "/" + m.group(2)
    m = re.match(r"^([A-Za-z]):/(.*)$", p)
    if m:
        return "/mnt/" + m.group(1).lower() + "/" + m.group(2)
    return p

REQUIRED_INVENTORY_COLS = [
    "path", "item_type", "size_bytes", "extension", "is_reparse",
    "blocked", "is_git_boundary", "sensitive", "depth",
]

REQUIRED_ACTIONS_COLS = [
    "action_id", "proposed_action", "source_path", "proposed_destination",
    "destination_policy_status", "classification", "reason", "confidence",
    "reversible", "blocked", "block_reason", "required_approval", "source_evidence",
]


def scan_file_for_secrets(path):
    """Return dict of category -> count for the file. Never prints matches."""
    found = {}
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except Exception:
        return {}
    for name, pattern in SECRET_PATTERNS.items():
        m = pattern.findall(content)
        if m:
            found[name] = len(m)
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True, help="Review run directory")
    ap.add_argument("--target", required=True, help="Explicit target directory that was reviewed")
    args = ap.parse_args()

    results = []
    ok = True

    # 1. Required pre-existing outputs present (VALIDATION_RESULTS.md is generated by this tool)
    for out in REQUIRED_PRE_EXISTING_OUTPUTS:
        p = os.path.join(args.run, out)
        if os.path.isfile(p):
            results.append(("PASS", f"required output present: {out}", p))
        else:
            results.append(("FAIL", f"required output MISSING: {out}", p))
            ok = False

    # 2. Inventory structure + path safety
    inv_path = os.path.join(args.run, "INVENTORY.csv")
    if os.path.isfile(inv_path):
        try:
            with open(inv_path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                rows = list(reader)
                cols = reader.fieldnames or []
            missing_cols = [c for c in REQUIRED_INVENTORY_COLS if c not in cols]
            if missing_cols:
                results.append(("FAIL", f"INVENTORY missing columns: {missing_cols}", inv_path))
                ok = False
            else:
                results.append(("PASS", f"INVENTORY has all required columns ({len(rows)} rows)", inv_path))
            # path-safety: no inventoried path outside target (normalize UNC/WSL/Windows)
            norm_target = normalize_path(args.target).rstrip("/")
            outside = []
            for r in rows:
                p = normalize_path(r.get("path", "")).rstrip("/")
                if p and not (p == norm_target or p.startswith(norm_target + "/")):
                    outside.append(p)
            if outside:
                results.append(("FAIL", f"Path-safety: {len(outside)} inventoried path(s) outside explicit target", inv_path))
                ok = False
            else:
                results.append(("PASS", "Path-safety: no inventoried path outside explicit target", inv_path))
            # reparse not followed: any reparse item must be blocked, and no descendent of a reparse dir present
            reparse_items = [r for r in rows if str(r.get("is_reparse","")).lower() == "true"]
            unblocked_reparse = [r for r in reparse_items if str(r.get("blocked","")).lower() != "true"]
            if unblocked_reparse:
                results.append(("FAIL", f"{len(unblocked_reparse)} reparse item(s) not blocked", inv_path))
                ok = False
            else:
                results.append(("PASS", f"Reparse handling: {len(reparse_items)} reparse item(s) all blocked", inv_path))
            # sensitive content not spilled: sensitive flag should not be printed content
        except Exception as e:
            results.append(("FAIL", f"Could not read INVENTORY.csv: {e}", inv_path))
            ok = False

    # 3. Proposed actions all blocked
    act_path = os.path.join(args.run, "PROPOSED_ACTIONS.csv")
    if os.path.isfile(act_path):
        try:
            with open(act_path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                arows = list(reader)
                acols = reader.fieldnames or []
            missing_cols = [c for c in REQUIRED_ACTIONS_COLS if c not in acols]
            if missing_cols:
                results.append(("FAIL", f"PROPOSED_ACTIONS missing columns: {missing_cols}", act_path))
                ok = False
            else:
                results.append(("PASS", f"PROPOSED_ACTIONS has required columns ({len(arows)} rows)", act_path))
            not_blocked = [a for a in arows if str(a.get("blocked","")).lower() != "true"]
            if not_blocked:
                results.append(("FAIL", f"{len(not_blocked)} proposed action(s) NOT blocked (v1 requires all blocked)", act_path))
                ok = False
            else:
                results.append(("PASS", f"All {len(arows)} proposed action(s) blocked=true on v1", act_path))
        except Exception as e:
            results.append(("FAIL", f"Could not read PROPOSED_ACTIONS.csv: {e}", act_path))
            ok = False

    # 4. Secret-safety audit across the whole run dir
    secret_issues = {}
    sensitive_dirs_followed = []
    for root, dirs, files in os.walk(args.run):
        # skip hidden .git if present in fixture copies
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        # detect whether any sensitive-looking directory was present in inventory paths
        for f in files:
            fp = os.path.join(root, f)
            for cat, count in scan_file_for_secrets(fp).items():
                secret_issues.setdefault(cat, 0)
                secret_issues[cat] += count
    if secret_issues:
        results.append(("FAIL", f"Secret-safety: potential secret patterns found by category (counts only): {secret_issues}", args.run))
        ok = False
    else:
        results.append(("PASS", "Secret-safety: no secret patterns detected in any output", args.run))

    # 5. Content-inspection stop: ensure the sensitive-looking file body text did NOT appear literally
    #    (validated by absence of the secret-placeholder specific marker string in outputs is handled by secret scan)

    # Write VALIDATION_RESULTS.md
    report_lines = []
    report_lines.append("# VALIDATION_RESULTS.md")
    report_lines.append("")
    report_lines.append(f"**Run:** {args.run}")
    report_lines.append(f"**Explicit target:** {args.target}")
    report_lines.append(f"**Status:** {'PASS' if ok else 'FAIL'}")
    report_lines.append("")
    report_lines.append("## Checks")
    report_lines.append("")
    report_lines.append("| Result | Check | Evidence |")
    report_lines.append("|---|---|---|")
    for res, check, ev in results:
        report_lines.append(f"| {res} | {check} | `{ev}` |")
    if secret_issues:
        report_lines.append("")
        report_lines.append("## Secret-safety detail (category + count ONLY — no values)")
        for cat, count in sorted(secret_issues.items()):
            report_lines.append(f"- {cat}: {count}")
    report_lines.append("")
    report_lines.append(f"**No secret values were printed.** Validation is category/count based.")
    report_lines.append(f"**No sensitive content was read into outputs.**")

    val_path = os.path.join(args.run, "VALIDATION_RESULTS.md")
    with open(val_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines) + "\n")
    results.append(("INFO", f"VALIDATION_RESULTS.md written with {'PASS' if ok else 'FAIL'}", val_path))

    print("\n".join(f"[{r}] {c} — {e}" for r, c, e in results))
    print(f"\nOVERALL: {'PASS' if ok else 'FAIL'}")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
