#!/usr/bin/env python3
"""
validate_review_output.py — Validate a Computer File Steward v1.0.1 review run.

Checks:
  1. All six required review outputs exist under the run directory.
  2. INVENTORY.csv has the required columns (incl. metadata_status) and no
     reparse points were followed (a file/dir whose path resolves outside the
     explicit target).
  3. PROPOSED_ACTIONS.csv: every row has blocked=true (v1 advisory only).
  4. Secret-safety audit: no password values, API keys, OAuth tokens, private
     keys, recovery codes, .env contents, credential-bearing URLs, household
     identifiers, or content excerpts from sensitive files. Reports category
     + count only — never prints matches.
  5. Path-safety: no path outside the explicit fixture target was inventoried
     as target content (uses the shared canonical path model).
  6. Metadata: ordinary accessible items with metadata_status='ok' have
     nonblank created/modified timestamps (Correction B).

USAGE:
    python3 validate_review_output.py --run <run-directory> --target <explicit-target>
"""
import argparse
import csv
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from path_canonicalize import target_contains

# Secret patterns (test only for presence/count — never print matched values)
SECRET_PATTERNS = {
    "api_key": re.compile(r"(?i)\b(api[_-]?key|api[_-]?token|secret[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|bearer)\s*[=:]\s*\S+"),
    "aws_key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "private_key_block": re.compile(r"-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----"),
    "openai_key": re.compile(r"\bsk-[A-Za-z0-9]{20,}\b"),
    "google_key": re.compile(r"\bAIza[0-9A-Za-z_-]{20,}\b"),
    "github_pat": re.compile(r"\bgh[pousr]_[0-9A-Za-z]{36,}\b"),
    "credential_url": re.compile(r"[a-zA-Z][a-zA-Z0-9+.-]*://[^\s/@]+:[^\s/@]+@[^\s]+"),
    "password_field": re.compile(r"(?i)\b(password|passwd|pwd|secret)\s*[=:]\s*\S+"),
    "recovery_code": re.compile(r"(?i)\b(recovery[-\s]?code|mfa[-\s]?seed|2fa[-\s]?code|otp[-\s]?secret)\s*[=:]\s*\S+"),
    "household_id": re.compile(r"(?i)\b(particulars|date\s+of\s+birth|medicare\s+no|tax\s+file\s+no|drivers?\s+licence\s+no)\b"),
}

REQUIRED_PRE_EXISTING_OUTPUTS = [
    "DIRECTORY_REVIEW.md",
    "INVENTORY.csv",
    "PROPOSED_ACTIONS.csv",
    "UNKNOWNS.md",
    "RUN_METADATA.json",
]

SENSITIVE_MARKERS = ["secret", "credential", "password", "token", ".env", "key.pem",
                     "id_rsa", "bitwarden", "recovery-code", "mfa", "household",
                     "conversations.json", "clinical", "legal", "financial",
                     "mailbox", "upload", "database", "briefing"]

REQUIRED_INVENTORY_COLS = [
    "path", "item_type", "size_bytes", "extension", "is_reparse",
    "blocked", "is_git_boundary", "sensitive", "depth",
]

REQUIRED_ACTIONS_COLS = [
    "action_id", "proposed_action", "source_path", "proposed_destination",
    "destination_policy_status", "classification", "reason", "confidence",
    "reversible", "blocked", "block_reason", "required_approval", "source_evidence",
]


def scan_file_for_secrets(path):
    """Return dict of category -> count for the file. Never prints matches."""
    found = {}
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except Exception:
        return {}
    for name, pattern in SECRET_PATTERNS.items():
        m = pattern.findall(content)
        if m:
            found[name] = len(m)
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True, help="Review run directory")
    ap.add_argument("--target", required=True, help="Explicit target directory that was reviewed")
    args = ap.parse_args()

    results = []
    ok = True

    # 1. Required pre-existing outputs present (VALIDATION_RESULTS.md is generated by this tool)
    for out in REQUIRED_PRE_EXISTING_OUTPUTS:
        p = os.path.join(args.run, out)
        if os.path.isfile(p):
            results.append(("PASS", f"required output present: {out}", p))
        else:
            results.append(("FAIL", f"required output MISSING: {out}", p))
            ok = False

    # 2. Inventory structure + path safety + metadata
    inv_path = os.path.join(args.run, "INVENTORY.csv")
    if os.path.isfile(inv_path):
        try:
            with open(inv_path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                rows = list(reader)
                cols = reader.fieldnames or []
            missing_cols = [c for c in REQUIRED_INVENTORY_COLS if c not in cols]
            if missing_cols:
                results.append(("FAIL", f"INVENTORY missing columns: {missing_cols}", inv_path))
                ok = False
            else:
                results.append(("PASS", f"INVENTORY has all required columns ({len(rows)} rows)", inv_path))
            # path-safety via shared canonical model (fail closed on unprovable)
            outside = []
            unresolved = []
            for r in rows:
                cpath = r.get("path", "")
                res = target_contains(args.target, cpath)
                if res is True:
                    continue
                if res is False:
                    outside.append(cpath)
                else:
                    unresolved.append(cpath)
            if outside:
                results.append(("FAIL", f"Path-safety: {len(outside)} inventoried path(s) outside explicit target", inv_path))
                ok = False
            elif unresolved:
                results.append(("FAIL", f"Path-safety: {len(unresolved)} path(s) could not be proven within target (fail closed)", inv_path))
                ok = False
            else:
                results.append(("PASS", "Path-safety: all inventoried paths within explicit target", inv_path))
            # reparse not followed: any reparse item must be blocked
            reparse_items = [r for r in rows if str(r.get("is_reparse", "")).lower() == "true"]
            unblocked_reparse = [r for r in reparse_items if str(r.get("blocked", "")).lower() != "true"]
            if unblocked_reparse:
                results.append(("FAIL", f"{len(unblocked_reparse)} reparse item(s) not blocked", inv_path))
                ok = False
            else:
                results.append(("PASS", f"Reparse handling: {len(reparse_items)} reparse item(s) all blocked", inv_path))
            # metadata: ordinary accessible items with metadata_status='ok' have nonblank created+modified
            bad_ts = []
            for r in rows:
                ms = str(r.get("metadata_status", "")).strip()
                # A UNREADABLE/noaccess reparse is fine to have blanks; only require ok-status items
                if ms == "ok" and not str(r.get("is_reparse", "")).lower() == "true":
                    if not r.get("created") or not r.get("modified"):
                        bad_ts.append(r.get("path"))
            if bad_ts:
                results.append(("FAIL", f"Metadata: {len(bad_ts)} accessible item(s) with metadata_status='ok' but blank created/modified", inv_path))
                ok = False
            else:
                results.append(("PASS", "Metadata: accessible ok-status items have nonblank created/modified timestamps", inv_path))
        except Exception as e:
            results.append(("FAIL", f"Could not read INVENTORY.csv: {e}", inv_path))
            ok = False

    # 3. Proposed actions all blocked
    act_path = os.path.join(args.run, "PROPOSED_ACTIONS.csv")
    if os.path.isfile(act_path):
        try:
            with open(act_path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                arows = list(reader)
                acols = reader.fieldnames or []
            missing_cols = [c for c in REQUIRED_ACTIONS_COLS if c not in acols]
            if missing_cols:
                results.append(("FAIL", f"PROPOSED_ACTIONS missing columns: {missing_cols}", act_path))
                ok = False
            else:
                results.append(("PASS", f"PROPOSED_ACTIONS has required columns ({len(arows)} rows)", act_path))
            not_blocked = [a for a in arows if str(a.get("blocked", "")).lower() != "true"]
            if not_blocked:
                results.append(("FAIL", f"{len(not_blocked)} proposed action(s) NOT blocked (v1 requires all blocked)", act_path))
                ok = False
            else:
                results.append(("PASS", f"All {len(arows)} proposed action(s) blocked=true on v1", act_path))
        except Exception as e:
            results.append(("FAIL", f"Could not read PROPOSED_ACTIONS.csv: {e}", act_path))
            ok = False

    # 4. Secret-safety audit across the whole run dir
    secret_issues = {}
    for root, dirs, files in os.walk(args.run):
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for f in files:
            fp = os.path.join(root, f)
            for cat, count in scan_file_for_secrets(fp).items():
                secret_issues.setdefault(cat, 0)
                secret_issues[cat] += count
    if secret_issues:
        results.append(("FAIL", f"Secret-safety: potential secret patterns found by category (counts only): {secret_issues}", args.run))
        ok = False
    else:
        results.append(("PASS", "Secret-safety: no secret patterns detected in any output", args.run))

    # Write VALIDATION_RESULTS.md
    report_lines = []
    report_lines.append("# VALIDATION_RESULTS.md")
    report_lines.append("")
    report_lines.append(f"**Run:** {args.run}")
    report_lines.append(f"**Explicit target:** {args.target}")
    report_lines.append(f"**Status:** {'PASS' if ok else 'FAIL'}")
    report_lines.append("")
    report_lines.append("## Checks")
    report_lines.append("")
    report_lines.append("| Result | Check | Evidence |")
    report_lines.append("|---|---|---|")
    for res, check, ev in results:
        report_lines.append(f"| {res} | {check} | `{ev}` |")
    if secret_issues:
        report_lines.append("")
        report_lines.append("## Secret-safety detail (category + count ONLY — no values)")
        for cat, count in sorted(secret_issues.items()):
            report_lines.append(f"- {cat}: {count}")
    report_lines.append("")
    report_lines.append("**No secret values were printed.** Validation is category/count based.")
    report_lines.append("**No sensitive content was read into outputs.**")

    val_path = os.path.join(args.run, "VALIDATION_RESULTS.md")
    with open(val_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines) + "\n")
    results.append(("INFO", f"VALIDATION_RESULTS.md written with {'PASS' if ok else 'FAIL'}", val_path))

    print("\n".join(f"[{r}] {c} — {e}" for r, c, e in results))
    print(f"\nOVERALL: {'PASS' if ok else 'FAIL'}")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
